# required:
github.username: hexxone

github.scrape_users:
    - hexxone
    - viertel97
    - Onyxmoon
    - SiegelDaniel
    - Whitebock
    - GreenDonkey
    - Duck-Mc-Muffin
    - ReinhardtJ
    - Kaycon
    - OfflineOnline